# Generated by Django 6.0.2 on 2026-02-13 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='descripton',
            new_name='description',
        ),
    ]
