# Generated by Django 6.0.2 on 2026-02-14 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_participant'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='qr_image',
            field=models.ImageField(blank=True, upload_to='qrcodes/'),
        ),
    ]
